WITH TARGET_INFO AS (
    SELECT
        TRUNC(STDS_DTM, 'MM') AS TARGET_MONTH_START,
        CUST_ID               AS TARGET_CUST
    FROM STR_ALERT_INFO_BASE
    WHERE STR_ALERT_ID = :alert_id
    FETCH FIRST 1 ROW ONLY           
MAX_RULE_LOG AS (
    SELECT STR_RULE_ID, MAX(STR_RULE_SEQ) AS MAX_SEQ
    FROM STR_RULE_MNGT_LOG
    GROUP BY STR_RULE_ID
)
SELECT
    TO_CHAR(A.STDS_DTM, 'YYYY-MM-DD') AS STDS_DTM,  
    A.CUST_ID,
    A.STR_RULE_ID,
    A.STR_ALERT_ID,
    A.STR_RPT_MNGT_NO,
    B.STR_RULE_NM,
    B.STR_RULE_DTL_EXP,
    B.STR_RULE_EXTR_COND_CTNT,
    B.AML_BSS_CTNT
FROM STR_ALERT_INFO_BASE A
CROSS JOIN TARGET_INFO T
LEFT JOIN MAX_RULE_LOG M
       ON M.STR_RULE_ID = A.STR_RULE_ID
LEFT JOIN STR_RULE_MNGT_LOG B
       ON B.STR_RULE_ID = M.STR_RULE_ID
      AND B.STR_RULE_SEQ = M.MAX_SEQ
WHERE A.STDS_DTM >= T.TARGET_MONTH_START
  AND A.STDS_DTM <  ADD_MONTHS(T.TARGET_MONTH_START, 1)
  AND A.CUST_ID = T.TARGET_CUST
ORDER BY A.STDS_DTM ASC;             