
select
    KYC_CORP_EXAM_LIST.CUST_KO_NM "법인명",
    KYC_CORP_EXAM_LIST.CUST_EN_NM "법인 영문명",
    KYC_CUST_BASE.CUST_ID "CID",
    KYC_MEM_BASE.MEM_ID                         "MID",
    AES_DECRYPT(KYC_CUST_BASE.RLNM_CERT_VAL)    "사업자등록번호",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_TYPE_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.CORP_TYPE_CD) "법인유형",
    SM_CD_DTL.AML_DTL_CD_NM                     "업종",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'MKP_PTCP_STEP_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.MKP_PTCP_STEP_CD) "시장참여단계",
    KYC_CORP_EXAM_LIST.CORP_ESTB_DT "설립일자",
    AES_DECRYPT(KYC_CORP_EXAM_LIST.CUST_EMAIL)  "E-mail",
    DM_SYS_NAT_BASE_1.NAT_KO_NM                 "설립국가",
    AES_DECRYPT(KYC_CORP_EXAM_LIST.CUST_TEL_NO) "대표번호",
    KYC_CORP_EXAM_LIST.ESTB_PUPS_CTNT "비영리단체 설립목적",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_BELSTD_TYPE_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.CORP_BELSTD_TYPE_CD) "상장여부",
    DM_SYS_NAT_BASE_1.LEN2_ABBR_NAT_CD          custNtnltCdLen2,
    DM_SYS_NAT_BASE_2.NAT_KO_NM                 "본점소재지국가",
    KYC_CORP_EXAM_LIST.CUST_ZIPCD "본점소재지우편번호",
    KYC_CORP_EXAM_LIST.CUST_ADDR "본점소재지주소",
    KYC_CORP_EXAM_LIST.CUST_DTL_ADDR "본점소재지상세주소",
    KYC_CORP_EXAM_LIST.POBS_PST_NAT_CD,
    DM_SYS_NAT_BASE_3.NAT_KO_NM                  "사업장소재지국가",
    KYC_CORP_EXAM_LIST.POBS_ZIPCD  "사업장소재지우편번호",
    KYC_CORP_EXAM_LIST.POBS_ADDR  "사업장소재지주소",
    KYC_CORP_EXAM_LIST.POBS_DTL_ADDR  "사업장소재지상세주소",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_TRAN_PUPS_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.TRAN_PUPS_CD) "거래목적",
    KYC_CORP_EXAM_LIST.TRAN_PUPS_DTL_CTNT "거래목적 기타-기재",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_PRMY_INCM_SURC_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.PRMY_INCM_SURC_CD) "주요소득의 원천",
    KYC_CORP_EXAM_LIST.PRMY_INCM_SURC_CTNT "주요소득의 원천 기타-기재",
    KYC_CORP_EXAM_LIST.DMST_DCL_TGT_VASP_YN "국내 신고 대상 가상자산사업자 여부",
    KYC_CORP_EXAM_LIST.VASP_ACTRPT_REG_NO,
    KYC_CORP_EXAM_LIST.VASP_ACTRPT_ISSUE_DTM,
    KYC_CORP_EXAM_LIST.VASP_ACTRPT_EXPR_DTM,
    KYC_CORP_EXAM_LIST.ISMS_CERT_NO,
    KYC_CORP_EXAM_LIST.ISMS_ISSUE_DTM,
    KYC_CORP_EXAM_LIST.ISMS_EXPR_DTM,
    KYC_NCUS_RELPR_BASE.RELPR_KO_NM "대리인명",
    KYC_NCUS_RELPR_BASE.RELPR_EN_NM "대리인영문명",
    KYC_CORP_RELPR_BASE.RELPR_ID "대리인고객ID",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'REAL_OWNR_IDEN_EXM_TGT_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.REAL_OWNR_IDEN_EXM_TGT_CD) "실제소유자식별 면제대상",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'REAL_OWNR_IDEN_EXM_TGT_TYPE_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.REAL_OWNR_IDEN_EXM_TGT_TYPE_CD) "면제 대상 구분",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'REAL_OWNR_IDEN_STEP_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.REAL_OWNR_IDEN_STEP_CD) "실제소유자 식별 단계",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_MM_AVG_SALES_RNGE_AMT_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.MM_AVG_SALES_RNGE_AMT_CD) "월 평균 매출액",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_DLNG_TRAN_FNDS_SURC_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.DLNG_TRAN_FNDS_SURC_CD) "매매거래의자금의원천상세",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_TOT_AST_SCL_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.TOT_AST_SCL_CD) "총 자산의 규모",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_MM_AVG_EXPT_TRAN_CNT_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.MM_AVG_EXPT_TRAN_CNT_CD) "월 평균 예상 거래 횟수",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'MM_AVG_EXPT_IO_TRAN_SCL_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.MM_AVG_EXPT_IO_TRAN_SCL_CD) "월 평균 예상 거래 규모(입출금)",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'MM_AVG_EXPT_AST_TRAN_SCL_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.MM_AVG_EXPT_AST_TRAN_SCL_CD) "월평균 예상 거래 규모(가상자산)",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_INCM_PTTN_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.INCM_PTTN_1_CD) "소득유형1",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_INCM_PTTN_RNGE_AMT_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.INCM_PTTN_1_RNGE_AMT_CD) "소득유형1소득구간",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_INCM_PTTN_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.INCM_PTTN_2_CD) "소득유형2",
    (select AML_DTL_CD_NM from SM_CD_DTL where AML_COMN_CD = 'CORP_INCM_PTTN_RNGE_AMT_CD' and AML_DTL_CD = KYC_CORP_EXAM_LIST.INCM_PTTN_2_RNGE_AMT_CD) "소득유형2소득구간"
from BTCAMLDB_OWN.KYC_CUST_BASE KYC_CUST_BASE
         inner join BTCAMLDB_OWN.KYC_MEM_BASE KYC_MEM_BASE
                    on KYC_CUST_BASE.CUST_ID = KYC_MEM_BASE.CUST_ID
         left join (select /*+ no_merge push_pred index_desc(KYC_CORP_EXAM_LIST IDX_KYC_CORP_EXAM_LIST_02) */
                        KYC_CORP_EXAM_LIST.*,
                        row_number() over (partition by KYC_CORP_EXAM_LIST.CUST_ID order by KYC_CORP_EXAM_LIST.KYC_EXAM_STRT_DTM desc) RN
                    from BTCAMLDB_OWN.KYC_CORP_EXAM_LIST KYC_CORP_EXAM_LIST
                    where KYC_CORP_EXAM_LIST.KYC_EXE_MEM_ID = 'A10441129A'
                      and KYC_CORP_EXAM_LIST.KYC_EXAM_STRT_DTM = '2025-08-20 15:54:43.624547') KYC_CORP_EXAM_LIST
                   on KYC_CORP_EXAM_LIST.KYC_EXE_MEM_ID = KYC_MEM_BASE.MEM_ID and KYC_CORP_EXAM_LIST.RN = 1
         left join BTCAMLDB_OWN.RA_CUST_RKAT_GRD_LIST RA_CUST_RKAT_GRD_LIST
                   on KYC_CORP_EXAM_LIST.CUST_ID = RA_CUST_RKAT_GRD_LIST.CUST_ID and
                      KYC_CORP_EXAM_LIST.RKAT_DTM = RA_CUST_RKAT_GRD_LIST.RKAT_DTM
         left join BTCAMLDB_OWN.SM_USER_BASE SM_USER_BASE_1
                   on KYC_CORP_EXAM_LIST.PAP_RVIW_TAPN_ID = SM_USER_BASE_1.AML_USER_ID
         left join BTCAMLDB_OWN.SM_USER_BASE SM_USER_BASE_2
                   on KYC_CORP_EXAM_LIST.KYC_RVIW_TAPN_ID = SM_USER_BASE_2.AML_USER_ID
         left join BTCAMLDB_OWN.SM_USER_BASE SM_USER_BASE_3
                   on KYC_CORP_EXAM_LIST.EXAM_RSLT_APRV_MAN_ID = SM_USER_BASE_3.AML_USER_ID
         left join BTCAMLDB_OWN.KYC_CORP_RELPR_BASE KYC_CORP_RELPR_BASE
                   on KYC_CORP_EXAM_LIST.CUST_ID = KYC_CORP_RELPR_BASE.CUST_ID and
                      KYC_CORP_EXAM_LIST.KYC_EXAM_STRT_DTM = KYC_CORP_RELPR_BASE.KYC_EXAM_STRT_DTM and
                      KYC_CORP_RELPR_BASE.RELPR_TYPE_CD = '003' and KYC_CORP_RELPR_BASE.DEL_YN = 'N'
         left join BTCAMLDB_OWN.KYC_NCUS_RELPR_BASE KYC_NCUS_RELPR_BASE
                   on KYC_CORP_EXAM_LIST.CUST_ID = KYC_NCUS_RELPR_BASE.CUST_ID and
                      KYC_CORP_EXAM_LIST.KYC_EXAM_STRT_DTM = KYC_NCUS_RELPR_BASE.KYC_EXAM_STRT_DTM and
                      KYC_NCUS_RELPR_BASE.RELPR_TYPE_CD = '003' and
                      KYC_NCUS_RELPR_BASE.RELPR_SEQ = KYC_CORP_RELPR_BASE.RELPR_SEQ
         left join BTCAMLDB_OWN.DM_SYS_NAT_BASE DM_SYS_NAT_BASE_1
                   on KYC_CORP_EXAM_LIST.CUST_NTNLT_CD = DM_SYS_NAT_BASE_1.LEN3_ABBR_NAT_CD
         left join BTCAMLDB_OWN.DM_SYS_NAT_BASE DM_SYS_NAT_BASE_2
                   on KYC_CORP_EXAM_LIST.CUST_LIVE_NAT_CD = DM_SYS_NAT_BASE_2.LEN3_ABBR_NAT_CD
         left join BTCAMLDB_OWN.DM_SYS_NAT_BASE DM_SYS_NAT_BASE_3
                   on KYC_CORP_EXAM_LIST.POBS_PST_NAT_CD = DM_SYS_NAT_BASE_3.LEN3_ABBR_NAT_CD
         left join BTCAMLDB_OWN.SM_CD_DTL SM_CD_DTL
                   on KYC_CORP_EXAM_LIST.BZTYP_TYPE_CD = SM_CD_DTL.AML_DTL_CD and
                      SM_CD_DTL.AML_COMN_CD = 'BZTYP_TYPE_CD'
where KYC_CUST_BASE.CUST_ID = :custId;
