-- 법인 고객 상세 정보 조회
-- 바인드 변수: :custId
SELECT
    KYC_CORP_EXAM_LIST.CUST_KO_NM "법인명",
    KYC_CORP_EXAM_LIST.CUST_EN_NM "법인 영문명",
    KYC_CUST_BASE.CUST_ID "CID",
    KYC_MEM_BASE.MEM_ID "MID",
    AES_DECRYPT(KYC_CUST_BASE.RLNM_CERT_VAL) "사업자등록번호",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_TYPE_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.CORP_TYPE_CD) "법인유형",
    SM_CD_DTL.AML_DTL_CD_NM "업종",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'MKP_PTCP_STEP_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.MKP_PTCP_STEP_CD) "시장참여단계",
    KYC_CORP_EXAM_LIST.CORP_ESTB_DT "설립일자",
    AES_DECRYPT(KYC_CORP_EXAM_LIST.CUST_EMAIL) "E-mail",
    DM_SYS_NAT_BASE_1.NAT_KO_NM "설립국가",
    AES_DECRYPT(KYC_CORP_EXAM_LIST.CUST_TEL_NO) "대표번호",
    KYC_CORP_EXAM_LIST.ESTB_PUPS_CTNT "비영리단체 설립목적",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_BELSTD_TYPE_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.CORP_BELSTD_TYPE_CD) "상장여부",
    DM_SYS_NAT_BASE_1.LEN2_ABBR_NAT_CD custNtnltCdLen2,
    DM_SYS_NAT_BASE_2.NAT_KO_NM "본점소재지국가",
    KYC_CORP_EXAM_LIST.CUST_ZIPCD "본점소재지우편번호",
    KYC_CORP_EXAM_LIST.CUST_ADDR "본점소재지주소",
    KYC_CORP_EXAM_LIST.CUST_DTL_ADDR "본점소재지상세주소",
    KYC_CORP_EXAM_LIST.POBS_PST_NAT_CD,
    DM_SYS_NAT_BASE_3.NAT_KO_NM "사업장소재지국가",
    KYC_CORP_EXAM_LIST.POBS_ZIPCD "사업장소재지우편번호",
    KYC_CORP_EXAM_LIST.POBS_ADDR "사업장소재지주소",
    KYC_CORP_EXAM_LIST.POBS_DTL_ADDR "사업장소재지상세주소",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_TRAN_PUPS_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.TRAN_PUPS_CD) "거래목적",
    KYC_CORP_EXAM_LIST.TRAN_PUPS_DTL_CTNT "거래목적 기타-기재",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_PRMY_INCM_SURC_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.PRMY_INCM_SURC_CD) "주요소득의 원천",
    KYC_CORP_EXAM_LIST.PRMY_INCM_SURC_CTNT "주요소득의 원천 기타-기재",
    KYC_CORP_EXAM_LIST.DMST_DCL_TGT_VASP_YN "국내 신고 대상 가상자산사업자 여부",
    KYC_CORP_EXAM_LIST.VASP_ACTRPT_REG_NO,
    KYC_CORP_EXAM_LIST.VASP_ACTRPT_ISSUE_DTM,
    KYC_CORP_EXAM_LIST.VASP_ACTRPT_EXPR_DTM,
    KYC_CORP_EXAM_LIST.ISMS_CERT_NO,
    KYC_CORP_EXAM_LIST.ISMS_ISSUE_DTM,
    KYC_CORP_EXAM_LIST.ISMS_EXPR_DTM,
    KYC_NCUS_RELPR_BASE.RELPR_KO_NM "대리인명",
    KYC_NCUS_RELPR_BASE.RELPR_EN_NM "대리인영문명",
    KYC_CORP_RELPR_BASE.RELPR_ID "대리인고객ID",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'REAL_OWNR_IDEN_EXM_TGT_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.REAL_OWNR_IDEN_EXM_TGT_CD) "실제소유자식별 면제대상",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'REAL_OWNR_IDEN_EXM_TGT_TYPE_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.REAL_OWNR_IDEN_EXM_TGT_TYPE_CD) "면제 대상 구분",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'REAL_OWNR_IDEN_STEP_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.REAL_OWNR_IDEN_STEP_CD) "실제소유자 식별 단계",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_MM_AVG_SALES_RNGE_AMT_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.MM_AVG_SALES_RNGE_AMT_CD) "월 평균 매출액",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_DLNG_TRAN_FNDS_SURC_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.DLNG_TRAN_FNDS_SURC_CD) "매매거래의자금의원천상세",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_TOT_AST_SCL_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.TOT_AST_SCL_CD) "총 자산의 규모",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_MM_AVG_EXPT_TRAN_CNT_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.MM_AVG_EXPT_TRAN_CNT_CD) "월 평균 예상 거래 횟수",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'MM_AVG_EXPT_IO_TRAN_SCL_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.MM_AVG_EXPT_IO_TRAN_SCL_CD) "월 평균 예상 거래 규모(입출금)",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'MM_AVG_EXPT_AST_TRAN_SCL_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.MM_AVG_EXPT_AST_TRAN_SCL_CD) "월평균 예상 거래 규모(가상자산)",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_INCM_PTTN_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.INCM_PTTN_1_CD) "소득유형1",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_INCM_PTTN_RNGE_AMT_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.INCM_PTTN_1_RNGE_AMT_CD) "소득유형1소득구간",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_INCM_PTTN_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.INCM_PTTN_2_CD) "소득유형2",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_INCM_PTTN_RNGE_AMT_CD' AND AML_DTL_CD = KYC_CORP_EXAM_LIST.INCM_PTTN_2_RNGE_AMT_CD) "소득유형2소득구간"
FROM BTCAMLDB_OWN.KYC_CUST_BASE KYC_CUST_BASE
INNER JOIN BTCAMLDB_OWN.KYC_MEM_BASE KYC_MEM_BASE
    ON KYC_CUST_BASE.CUST_ID = KYC_MEM_BASE.CUST_ID
LEFT JOIN (
    SELECT /*+ no_merge push_pred index_desc(KYC_CORP_EXAM_LIST IDX_KYC_CORP_EXAM_LIST_02) */
        KYC_CORP_EXAM_LIST.*,
        ROW_NUMBER() OVER (PARTITION BY KYC_CORP_EXAM_LIST.CUST_ID ORDER BY KYC_CORP_EXAM_LIST.KYC_EXAM_STRT_DTM DESC) RN
    FROM BTCAMLDB_OWN.KYC_CORP_EXAM_LIST KYC_CORP_EXAM_LIST
    WHERE KYC_CORP_EXAM_LIST.CUST_ID = :custId
) KYC_CORP_EXAM_LIST
    ON KYC_CORP_EXAM_LIST.CUST_ID = KYC_CUST_BASE.CUST_ID 
    AND KYC_CORP_EXAM_LIST.RN = 1
LEFT JOIN BTCAMLDB_OWN.RA_CUST_RKAT_GRD_LIST RA_CUST_RKAT_GRD_LIST
    ON KYC_CORP_EXAM_LIST.CUST_ID = RA_CUST_RKAT_GRD_LIST.CUST_ID 
    AND KYC_CORP_EXAM_LIST.RKAT_DTM = RA_CUST_RKAT_GRD_LIST.RKAT_DTM
LEFT JOIN BTCAMLDB_OWN.SM_USER_BASE SM_USER_BASE_1
    ON KYC_CORP_EXAM_LIST.PAP_RVIW_TAPN_ID = SM_USER_BASE_1.AML_USER_ID
LEFT JOIN BTCAMLDB_OWN.SM_USER_BASE SM_USER_BASE_2
    ON KYC_CORP_EXAM_LIST.KYC_RVIW_TAPN_ID = SM_USER_BASE_2.AML_USER_ID
LEFT JOIN BTCAMLDB_OWN.SM_USER_BASE SM_USER_BASE_3
    ON KYC_CORP_EXAM_LIST.EXAM_RSLT_APRV_MAN_ID = SM_USER_BASE_3.AML_USER_ID
LEFT JOIN BTCAMLDB_OWN.KYC_CORP_RELPR_BASE KYC_CORP_RELPR_BASE
    ON KYC_CORP_EXAM_LIST.CUST_ID = KYC_CORP_RELPR_BASE.CUST_ID 
    AND KYC_CORP_EXAM_LIST.KYC_EXAM_STRT_DTM = KYC_CORP_RELPR_BASE.KYC_EXAM_STRT_DTM 
    AND KYC_CORP_RELPR_BASE.RELPR_TYPE_CD = '003' 
    AND KYC_CORP_RELPR_BASE.DEL_YN = 'N'
LEFT JOIN BTCAMLDB_OWN.KYC_NCUS_RELPR_BASE KYC_NCUS_RELPR_BASE
    ON KYC_CORP_EXAM_LIST.CUST_ID = KYC_NCUS_RELPR_BASE.CUST_ID 
    AND KYC_CORP_EXAM_LIST.KYC_EXAM_STRT_DTM = KYC_NCUS_RELPR_BASE.KYC_EXAM_STRT_DTM 
    AND KYC_NCUS_RELPR_BASE.RELPR_TYPE_CD = '003' 
    AND KYC_NCUS_RELPR_BASE.RELPR_SEQ = KYC_CORP_RELPR_BASE.RELPR_SEQ
LEFT JOIN BTCAMLDB_OWN.DM_SYS_NAT_BASE DM_SYS_NAT_BASE_1
    ON KYC_CORP_EXAM_LIST.CUST_NTNLT_CD = DM_SYS_NAT_BASE_1.LEN3_ABBR_NAT_CD
LEFT JOIN BTCAMLDB_OWN.DM_SYS_NAT_BASE DM_SYS_NAT_BASE_2
    ON KYC_CORP_EXAM_LIST.CUST_LIVE_NAT_CD = DM_SYS_NAT_BASE_2.LEN3_ABBR_NAT_CD
LEFT JOIN BTCAMLDB_OWN.DM_SYS_NAT_BASE DM_SYS_NAT_BASE_3
    ON KYC_CORP_EXAM_LIST.POBS_PST_NAT_CD = DM_SYS_NAT_BASE_3.LEN3_ABBR_NAT_CD
LEFT JOIN BTCAMLDB_OWN.SM_CD_DTL SM_CD_DTL
    ON KYC_CORP_EXAM_LIST.BZTYP_TYPE_CD = SM_CD_DTL.AML_DTL_CD 
    AND SM_CD_DTL.AML_COMN_CD = 'BZTYP_TYPE_CD'
WHERE KYC_CUST_BASE.CUST_ID = :custId;