-- customer_unified_info.sql
-- 고객 기본 정보 + 상세 정보 통합 쿼리 (개인/법인 모두 포함)
-- MID 정보 추가 (KYC_MEM_BASE 또는 KYC_CUST_BASE에서 가져옴)
-- 바인드 변수: :custId (1번 사용)

SELECT 
    -- ========== 기본 식별 정보 ==========
    c.CUST_ID AS "고객ID",
    COALESCE(m.MEM_ID, c.KYC_EXE_MEM_ID) AS "MID",
    COALESCE(ce.CUST_KO_NM, c.CUST_KO_NM) AS "성명",
    COALESCE(ce.CUST_EN_NM, c.CUST_EN_NM) AS "영문명",
    
    -- ========== 고객 구분 및 상태 ==========
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CUST_TYPE_CD' AND AML_DTL_CD = c.CUST_TYPE_CD) AS "고객구분",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CUST_RKGD_CD' AND AML_DTL_CD = ra.cust_rkgd_cd) AS "RA등급",
    CASE
        WHEN ce.AML_RSLT_CD = '200' THEN 'WLF 검토대기'
        WHEN ce.AML_RSLT_CD = '400' THEN '거래거절'
        WHEN ce.AML_RSLT_CD = '600' THEN 'CDD'
        WHEN ce.AML_RSLT_CD = '700' THEN 'EDD'
        WHEN ce.AML_RSLT_CD = '800' THEN 'EEDD'
        WHEN c.AML_RSLT_CD = '200' THEN 'WLF 검토대기'
        WHEN c.AML_RSLT_CD = '400' THEN '거래거절'
        WHEN c.AML_RSLT_CD = '600' THEN 'CDD'
        WHEN c.AML_RSLT_CD = '700' THEN 'EDD'
        WHEN c.AML_RSLT_CD = '800' THEN 'EEDD'
        ELSE NULL
    END AS "위험등급",
    c.CLB_YN AS "고액자산가",
    
    -- ========== 신원 정보 ==========
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'RLNM_CERT_CD' AND AML_DTL_CD = c.RLNM_CERT_CD) AS "실명번호구분",
    AES_DECRYPT(c.RLNM_CERT_VAL) AS "실명번호",
    COALESCE(c.CUST_BDAY, ce.CORP_ESTB_DT, c.CORP_ESTB_DT) AS "생년월일/설립일",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CUST_GNDR_CD' AND AML_DTL_CD = c.CUST_GNDR_CD) AS "성별",
    
    -- ========== 연락처 정보 ==========
    COALESCE(AES_DECRYPT(ce.CUST_TEL_NO), AES_DECRYPT(c.CUST_TEL_NO)) AS "연락처",
    COALESCE(AES_DECRYPT(ce.CUST_EMAIL), AES_DECRYPT(c.CUST_EMAIL)) AS "이메일",
    
    -- ========== 국적 정보 ==========
    n1.NAT_KO_NM AS "국적",
    n1.LEN2_ABBR_NAT_CD AS "국적코드",
    
    -- ========== 거주지/본점 정보 ==========
    n2.NAT_KO_NM AS "거주지국가",
    COALESCE(ce.CUST_ZIPCD, c.CUST_ZIPCD) AS "거주지우편번호",
    COALESCE(ce.CUST_ADDR, c.CUST_ADDR) AS "거주지주소",
    COALESCE(ce.CUST_DTL_ADDR, c.CUST_DTL_ADDR) AS "거주지상세주소",
    
    -- ========== 직업/직장/업종 정보 ==========
    CASE
        WHEN c.CUST_TYPE_CD = '01' THEN  -- 개인
            CASE
                WHEN j.JOB_LV_2_NM IS NULL THEN j.JOB_LV_1_NM
                ELSE j.JOB_LV_1_NM || ' (' || j.JOB_LV_2_NM || ')'
            END
        ELSE  -- 법인
            COALESCE(bz.AML_DTL_CD_NM, b.AML_BZTYP_TYPE_CD_CTNT, c.BZTYP_DTL_CTNT)
    END AS "직업/업종",
    j.JOB_LV_1_NM AS "직업대분류",
    j.JOB_LV_2_NM AS "직업소분류",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'JTTL_CD' AND AML_DTL_CD = c.JTTL_CD) AS "직위",
    c.WPLC_NM AS "직장명",
    n3.NAT_KO_NM AS "직장국가",
    c.WPLC_ZIPCD AS "직장우편번호",
    c.WPLC_ADDR AS "직장주소",
    c.WPLC_DTL_ADDR AS "직장상세주소",
    
    -- ========== 거래 정보 ==========
    CASE
        WHEN c.CUST_TYPE_CD = '01' THEN  -- 개인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_TRAN_PUPS_CD' AND AML_DTL_CD = COALESCE(ce.TRAN_PUPS_CD, c.TRAN_PUPS_CD))
        ELSE  -- 법인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_TRAN_PUPS_CD' AND AML_DTL_CD = COALESCE(ce.TRAN_PUPS_CD, c.TRAN_PUPS_CD))
    END AS "거래목적",
    ce.TRAN_PUPS_DTL_CTNT AS "거래목적기타",
    
    -- ========== 자금/소득 정보 ==========
    CASE
        WHEN c.CUST_TYPE_CD = '01' THEN  -- 개인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_PRMY_INCM_SURC_CD' AND AML_DTL_CD = COALESCE(ce.PRMY_INCM_SURC_CD, c.PRMY_INCM_SURC_CD))
        ELSE  -- 법인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_PRMY_INCM_SURC_CD' AND AML_DTL_CD = COALESCE(ce.PRMY_INCM_SURC_CD, c.PRMY_INCM_SURC_CD))
    END AS "주요소득원천",
    ce.PRMY_INCM_SURC_CTNT AS "주요소득원천기타",
    
    CASE
        WHEN c.CUST_TYPE_CD = '01' THEN  -- 개인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_MM_AVG_INCM_RNGE_AMT_CD' AND AML_DTL_CD = COALESCE(ce.MM_AVG_INCM_RNGE_AMT_CD, c.MM_AVG_INCM_RNGE_AMT_CD))
        ELSE  -- 법인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_MM_AVG_SALES_RNGE_AMT_CD' AND AML_DTL_CD = COALESCE(ce.MM_AVG_SALES_RNGE_AMT_CD, c.MM_AVG_SALES_RNGE_AMT_CD))
    END AS "월평균소득/매출",
    
    CASE
        WHEN c.CUST_TYPE_CD = '01' THEN  -- 개인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_DLNG_TRAN_FNDS_SURC_CD' AND AML_DTL_CD = COALESCE(ce.DLNG_TRAN_FNDS_SURC_CD, c.DLNG_TRAN_FNDS_SURC_CD))
        ELSE  -- 법인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_DLNG_TRAN_FNDS_SURC_CD' AND AML_DTL_CD = COALESCE(ce.DLNG_TRAN_FNDS_SURC_CD, c.DLNG_TRAN_FNDS_SURC_CD))
    END AS "매매거래자금원천",
    
    CASE
        WHEN c.CUST_TYPE_CD = '01' THEN  -- 개인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_TOT_AST_SCL_CD' AND AML_DTL_CD = COALESCE(ce.TOT_AST_SCL_CD, c.TOT_AST_SCL_CD))
        ELSE  -- 법인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_TOT_AST_SCL_CD' AND AML_DTL_CD = COALESCE(ce.TOT_AST_SCL_CD, c.TOT_AST_SCL_CD))
    END AS "총자산규모",
    
    -- ========== 예상 거래 규모 ==========
    CASE
        WHEN c.CUST_TYPE_CD = '01' THEN  -- 개인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_MM_AVG_EXPT_TRAN_CNT_CD' AND AML_DTL_CD = COALESCE(ce.MM_AVG_EXPT_TRAN_CNT_CD, c.MM_AVG_EXPT_TRAN_CNT_CD))
        ELSE  -- 법인
            (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_MM_AVG_EXPT_TRAN_CNT_CD' AND AML_DTL_CD = COALESCE(ce.MM_AVG_EXPT_TRAN_CNT_CD, c.MM_AVG_EXPT_TRAN_CNT_CD))
    END AS "월평균예상거래횟수",
    
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'MM_AVG_EXPT_IO_TRAN_SCL_CD' AND AML_DTL_CD = COALESCE(ce.MM_AVG_EXPT_IO_TRAN_SCL_CD, c.MM_AVG_EXPT_IO_TRAN_SCL_CD)) AS "월평균예상거래규모_입출금",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'MM_AVG_EXPT_AST_TRAN_SCL_CD' AND AML_DTL_CD = COALESCE(ce.MM_AVG_EXPT_AST_TRAN_SCL_CD, c.MM_AVG_EXPT_AST_TRAN_SCL_CD)) AS "월평균예상거래규모_가상자산",
    
    -- ========== STR 관련 정보 ==========
    (SELECT COUNT(r.STR_RPT_MNGT_NO) 
     FROM BTCAMLDB_OWN.STR_RPT_BASE r 
     WHERE r.CUST_ID = c.CUST_ID 
       AND r.XML_CRET_FILE_NM IS NOT NULL) AS "STR보고건수",
    
    (SELECT TO_CHAR(MAX(r.STR_RPT_DTM), 'YYYY-MM-DD') 
     FROM BTCAMLDB_OWN.STR_RPT_BASE r 
     WHERE r.CUST_ID = c.CUST_ID 
       AND r.XML_CRET_FILE_NM IS NOT NULL) AS "최종STR보고일",
    
    (SELECT COUNT(*) 
     FROM BTCAMLDB_OWN.STR_ALERT_LIST a 
     WHERE a.CUST_ID = c.CUST_ID) AS "Alert건수",
    
    -- ========== 법인 전용 필드 ==========
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_TYPE_CD' AND AML_DTL_CD = ce.CORP_TYPE_CD)
    END AS "법인유형",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'BZTYP_TYPE_CD' AND AML_DTL_CD = ce.BZTYP_TYPE_CD)
    END AS "업종코드",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'MKP_PTCP_STEP_CD' AND AML_DTL_CD = ce.MKP_PTCP_STEP_CD)
    END AS "시장참여단계",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_BELSTD_TYPE_CD' AND AML_DTL_CD = COALESCE(ce.CORP_BELSTD_TYPE_CD, c.CORP_BELSTD_TYPE_CD))
    END AS "상장여부",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN c.CORP_REG_NO END AS "사업자등록번호",
    CASE WHEN c.CUST_TYPE_CD = '02' THEN ce.DMST_DCL_TGT_VASP_YN END AS "국내신고대상VASP여부",
    CASE WHEN c.CUST_TYPE_CD = '02' THEN ce.ESTB_PUPS_CTNT END AS "비영리단체설립목적",
    
    -- 사업장 정보 (법인)
    CASE WHEN c.CUST_TYPE_CD = '02' THEN n4.NAT_KO_NM END AS "사업장소재지국가",
    CASE WHEN c.CUST_TYPE_CD = '02' THEN ce.POBS_ZIPCD END AS "사업장우편번호",
    CASE 
        WHEN c.CUST_TYPE_CD = '02' AND ce.POBS_DTL_ADDR IS NOT NULL 
        THEN ce.POBS_ADDR || ' ' || ce.POBS_DTL_ADDR
        WHEN c.CUST_TYPE_CD = '02' 
        THEN ce.POBS_ADDR
        ELSE NULL
    END AS "사업장주소",
    
    -- 실제소유자 관련 (법인)
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'REAL_OWNR_IDEN_EXM_TGT_CD' AND AML_DTL_CD = ce.REAL_OWNR_IDEN_EXM_TGT_CD)
    END AS "실제소유자식별면제대상",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'REAL_OWNR_IDEN_EXM_TGT_TYPE_CD' AND AML_DTL_CD = ce.REAL_OWNR_IDEN_EXM_TGT_TYPE_CD)
    END AS "면제대상구분",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'REAL_OWNR_IDEN_STEP_CD' AND AML_DTL_CD = ce.REAL_OWNR_IDEN_STEP_CD)
    END AS "실제소유자식별단계",
    
    -- 소득유형 (법인)
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_INCM_PTTN_CD' AND AML_DTL_CD = ce.INCM_PTTN_1_CD)
    END AS "소득유형1",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_INCM_PTTN_RNGE_AMT_CD' AND AML_DTL_CD = ce.INCM_PTTN_1_RNGE_AMT_CD)
    END AS "소득유형1구간",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_INCM_PTTN_CD' AND AML_DTL_CD = ce.INCM_PTTN_2_CD)
    END AS "소득유형2",
    
    CASE WHEN c.CUST_TYPE_CD = '02' THEN
        (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'CORP_INCM_PTTN_RNGE_AMT_CD' AND AML_DTL_CD = ce.INCM_PTTN_2_RNGE_AMT_CD)
    END AS "소득유형2구간",
    
    -- VASP 관련 (법인)
    CASE WHEN c.CUST_TYPE_CD = '02' THEN ce.VASP_ACTRPT_REG_NO END AS "VASP신고수리번호",
    CASE WHEN c.CUST_TYPE_CD = '02' THEN TO_CHAR(ce.VASP_ACTRPT_ISSUE_DTM, 'YYYY-MM-DD') END AS "VASP신고수리일",
    CASE WHEN c.CUST_TYPE_CD = '02' THEN TO_CHAR(ce.VASP_ACTRPT_EXPR_DTM, 'YYYY-MM-DD') END AS "VASP신고수리만료일",
    
    -- ISMS 관련 (법인)
    CASE WHEN c.CUST_TYPE_CD = '02' THEN ce.ISMS_CERT_NO END AS "ISMS인증번호",
    CASE WHEN c.CUST_TYPE_CD = '02' THEN TO_CHAR(ce.ISMS_ISSUE_DTM, 'YYYY-MM-DD') END AS "ISMS발급일",
    CASE WHEN c.CUST_TYPE_CD = '02' THEN TO_CHAR(ce.ISMS_EXPR_DTM, 'YYYY-MM-DD') END AS "ISMS만료일",
    
    -- ========== KYC 심사 정보 ==========
    TO_CHAR(c.KYC_EXE_FNS_DTM, 'YYYY-MM-DD HH24:MI:SS') AS "KYC완료일시",
    (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'EXAM_RVIW_STAT_CD' AND AML_DTL_CD = c.EXAM_RVIW_STAT_CD) AS "심사상태"
    
FROM BTCAMLDB_OWN.KYC_CUST_BASE c
-- 회원 정보 (LEFT JOIN으로 MEM_BASE에 없어도 KYC_EXE_MEM_ID 사용 가능)
LEFT JOIN BTCAMLDB_OWN.KYC_MEM_BASE m
    ON c.CUST_ID = m.CUST_ID
-- RA 등급 (최신)
LEFT JOIN BTCAMLDB_OWN.RA_CUST_RKAT_GRD_LIST ra
    ON ra.CUST_ID = c.CUST_ID
    AND ra.RKAT_DTM = (
        SELECT MAX(sub_ra.RKAT_DTM) 
        FROM BTCAMLDB_OWN.RA_CUST_RKAT_GRD_LIST sub_ra 
        WHERE sub_ra.CUST_ID = c.CUST_ID
    )
-- 직업 정보
LEFT JOIN BTCAMLDB_OWN.KYC_JOB_BASE j
    ON j.AML_JOB_CD = c.JOB_CD
-- 업종 정보
LEFT JOIN BTCAMLDB_OWN.KYC_BZTYP_BASE b
    ON b.AML_BZTYP_TYPE_CD = c.BZTYP_TYPE_CD
-- 국적
LEFT JOIN BTCAMLDB_OWN.DM_SYS_NAT_BASE n1
    ON n1.LEN3_ABBR_NAT_CD = c.CUST_NTNLT_CD
-- 거주지 국가
LEFT JOIN BTCAMLDB_OWN.DM_SYS_NAT_BASE n2
    ON n2.LEN3_ABBR_NAT_CD = c.CUST_LIVE_NAT_CD
-- 직장 국가
LEFT JOIN BTCAMLDB_OWN.DM_SYS_NAT_BASE n3
    ON n3.LEN3_ABBR_NAT_CD = c.WPLC_PST_NAT_CD
-- 법인 정보 (최신 심사 정보)
LEFT JOIN (
    SELECT /*+ no_merge push_pred */
        ce_inner.*,
        ROW_NUMBER() OVER (PARTITION BY ce_inner.CUST_ID ORDER BY ce_inner.KYC_EXAM_STRT_DTM DESC) AS rn
    FROM BTCAMLDB_OWN.KYC_CORP_EXAM_LIST ce_inner
) ce
    ON ce.CUST_ID = c.CUST_ID 
    AND ce.rn = 1
-- 사업장 국가 (법인)
LEFT JOIN BTCAMLDB_OWN.DM_SYS_NAT_BASE n4
    ON n4.LEN3_ABBR_NAT_CD = ce.POBS_PST_NAT_CD
-- 업종 상세 (법인)
LEFT JOIN BTCAMLDB_OWN.SM_CD_DTL bz
    ON bz.AML_DTL_CD = ce.BZTYP_TYPE_CD 
    AND bz.AML_COMN_CD = 'BZTYP_TYPE_CD'
WHERE c.CUST_ID = :custId