-- 고객확인 주요 정보(개인)
-- 바인드 변수 :custId
select KYC_CUST_BASE.CUST_ID "고객ID",
       KYC_CUST_BASE.KYC_EXE_MEM_ID "MID",
       KYC_CUST_BASE.KYC_EXE_FNS_DTM,
       KYC_CUST_BASE.EXAM_RVIW_STAT_CD,
       KYC_CUST_BASE.CUST_KO_NM "성명",
       KYC_CUST_BASE.CUST_EN_NM "영문명",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'RLNM_CERT_CD' AND AML_DTL_CD = KYC_CUST_BASE.RLNM_CERT_CD) "실명번호 구분",
       AES_DECRYPT(KYC_CUST_BASE.RLNM_CERT_VAL) "실명번호",
       KYC_CUST_BASE.CUST_BDAY "생년월일",
       AES_DECRYPT(KYC_CUST_BASE.CUST_EMAIL)    "E-mail",
       QSysNatBaseDmEntity1.NAT_KO_NM "국적",
       AES_DECRYPT(KYC_CUST_BASE.CUST_TEL_NO)   "휴대폰 번호",
       QSysNatBaseDmEntity2.NAT_KO_NM "거주주소국가",
       KYC_CUST_BASE.CUST_ZIPCD "거주주소우편번호",
       KYC_CUST_BASE.CUST_ADDR "거주주소",
       KYC_CUST_BASE.CUST_DTL_ADDR "거주상세주소",
       KYC_JOB_BASE.JOB_LV_1_NM "직업/업종",
       KYC_JOB_BASE.JOB_LV_2_NM "직업/업종상세",
       KYC_CUST_BASE.WPLC_NM "직장명",
       QSysNatBaseDmEntity3.NAT_KO_NM "직장주소국가",
       KYC_CUST_BASE.WPLC_ZIPCD "직장주소우편번호",
       KYC_CUST_BASE.WPLC_ADDR "직장주소",
       KYC_CUST_BASE.WPLC_DTL_ADDR "직장상세주소",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_TRAN_PUPS_CD' AND AML_DTL_CD = KYC_CUST_BASE.TRAN_PUPS_CD) "거래목적",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_PRMY_INCM_SURC_CD' AND AML_DTL_CD = KYC_CUST_BASE.PRMY_INCM_SURC_CD) "주요 소득의 원천",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_MM_AVG_INCM_RNGE_AMT_CD' AND AML_DTL_CD = KYC_CUST_BASE.MM_AVG_INCM_RNGE_AMT_CD) "월 평균 소득액",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_DLNG_TRAN_FNDS_SURC_CD' AND AML_DTL_CD = KYC_CUST_BASE.DLNG_TRAN_FNDS_SURC_CD) "매매거래자금의원천상세",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_TOT_AST_SCL_CD' AND AML_DTL_CD = KYC_CUST_BASE.TOT_AST_SCL_CD) "총 자산의규모",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'PERS_MM_AVG_EXPT_TRAN_CNT_CD' AND AML_DTL_CD = KYC_CUST_BASE.MM_AVG_EXPT_TRAN_CNT_CD) "월 평균 예상 거래 횟수",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'JTTL_CD' AND AML_DTL_CD = KYC_CUST_BASE.JTTL_CD) "직위",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'MM_AVG_EXPT_IO_TRAN_SCL_CD' AND AML_DTL_CD = KYC_CUST_BASE.MM_AVG_EXPT_IO_TRAN_SCL_CD) "월평균예상거래규모(입출금)",
       (SELECT AML_DTL_CD_NM FROM SM_CD_DTL WHERE AML_COMN_CD = 'MM_AVG_EXPT_AST_TRAN_SCL_CD' AND AML_DTL_CD = KYC_CUST_BASE.MM_AVG_EXPT_AST_TRAN_SCL_CD) "월평균예상거래규모(가상자산)"
from BTCAMLDB_OWN.KYC_CUST_BASE KYC_CUST_BASE
         left join BTCAMLDB_OWN.KYC_JOB_BASE KYC_JOB_BASE
                   on KYC_CUST_BASE.JOB_CD = KYC_JOB_BASE.AML_JOB_CD
         left join BTCAMLDB_OWN.DM_SYS_NAT_BASE QSysNatBaseDmEntity1
                   on KYC_CUST_BASE.CUST_NTNLT_CD = QSysNatBaseDmEntity1.LEN3_ABBR_NAT_CD
         left join BTCAMLDB_OWN.DM_SYS_NAT_BASE QSysNatBaseDmEntity2
                   on KYC_CUST_BASE.CUST_LIVE_NAT_CD = QSysNatBaseDmEntity2.LEN3_ABBR_NAT_CD
         left join BTCAMLDB_OWN.DM_SYS_NAT_BASE QSysNatBaseDmEntity3
                   on KYC_CUST_BASE.WPLC_PST_NAT_CD = QSysNatBaseDmEntity3.LEN3_ABBR_NAT_CD
where KYC_CUST_BASE.CUST_ID = :custId;